### ISSUE TITLE
Filepath incorrect for accordion test pages on jsdoc

### ISSUE THREAD

**Issue by munrocape** [winktoolkit/wink#5]
[Live page](http://www.winktoolkit.org/documentation/symbols/wink.ui.layout.Accordion.html) links to 

[http://www.winktoolkit.org/wink/ui/layout/accordion/layout/test/test_accordion_1.html](http://www.winktoolkit.org/wink/ui/layout/accordion/layout/test/test_accordion_1.html)

when in actuality the correct page is at 

[http://www.winktoolkit.org/wink/ui/layout/accordion/test/test_accordion_1.html](http://www.winktoolkit.org/wink/ui/layout/accordion/test/test_accordion_1.html)

A extra `layout/` was added to the filepath which redirects to your page not found page.

**Comment by winktoolkit** [comment]
Thanks, corrected
